[system]
compatible=generic-arm64
bootloader=uboot
statusfile=/data/rauc/system.raucstatus

[keyring]
path=/etc/rauc/keyring.pem

[slot.bootloader.0]
device=/dev/vda1
type=raw
bootname=bootloader

[slot.rootfs.0]
device=/dev/vda2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/vda3
type=ext4
bootname=B
