require conf/machine/qemuarm64.conf

MACHINEOVERRIDES =. "qemuall:qemuarm64:"

MACHINE_FEATURES:append = " optee tpm snapd"

# Map to qemuarm64 kernel BSP so linux-yocto finds the right branch/defconfig
KMACHINE = "qemuarm64"

# U-Boot as bootloader (required for RAUC integration)
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
UBOOT_MACHINE = "qemu_arm64_defconfig"
BOOTLOADER_BINARY = "u-boot.bin"