BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "lliot-imx"
BBFILE_PATTERN_lliot-imx-image = "^${LAYERDIR}/"
BBFILE_PRIORITY_lliot-imx-image = "7"

LAYERSERIES_COMPAT_lliot-imx_image = "scarthgap"