BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "edge-imx-image"
BBFILE_PATTERN_edge-imx-image = "^${LAYERDIR}/"
BBFILE_PRIORITY_edge-imx-image = "7"

LAYERSERIES_COMPAT_edge-imx-image = "dunfell gatesgarth hardknott kirkstone langdale zeus scarthgap wrynose"