BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "liot-imx-image"
BBFILE_PATTERN_liot-imx-image = "^${LAYERDIR}/"
BBFILE_PRIORITY_liot-imx-image = "7"

LAYERSERIES_COMPAT_liot-imx_image = "scarthgap"